### ISSUE TITLE
Error in makeSummary: invalid json response body at https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3FprettyPrint%3Dfalse%26v%3D5A8UUovaSb8%26pbj%3D1&q=EgQDgW_cGKyZ9bEGIjDIbez6kcN4Ofhrrbcfy2T6brx1CtlOvEP6CvOF0rtGbElS0CP3ISqeUAkwFsUF2MgyAXJaAUM reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by jenny4711** [SuspiciousLookingOwl/youtubei#97] opened 2024-05-09 22:29 UTC
**Describe the bug**
Error in makeSummary: invalid json response body at https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3FprettyPrint%3Dfalse%26v%3D5A8UUovaSb8%26pbj%3D1&q=EgQDgW_cGKyZ9bEGIjDIbez6kcN4Ofhrrbcfy2T6brx1CtlOvEP6CvOF0rtGbElS0CP3ISqeUAkwFsUF2MgyAXJaAUM reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Until a few days ago, it was working fine, but since 4-5 days ago, this error has been coming up. If you remove youtubei, that error does not appear. However, because I need a transcript, I have to use youtubei, so I am reporting this issue.
**my function**
const youtube = new Client();
async function makeSummary(req,res){
const { videoId, lang, ask, email } = req.body;
.....
const transcript = await youtube.getVideoTranscript(videoId);
console.log(transcript,'transcript')

}
**result**
Error in makeSummary: invalid json response body at https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3FprettyPrint%3Dfalse%26v%3D5A8UUovaSb8%26pbj%3D1&q=EgQDgW_cGKyZ9bEGIjDIbez6kcN4Ofhrrbcfy2T6brx1CtlOvEP6CvOF0rtGbElS0CP3ISqeUAkwFsUF2MgyAXJaAUM reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by SuspiciousLookingOwl** [comment] 2024-05-11 06:01
This works fine on my end
```ts
const client = new Client();
const transcript = await client.getVideoTranscript("5A8UUovaSb8");
console.log(transcript);
```

It seems like your error is caused by YouTube detecting your IP as malicious (can be caused by sending too many requests with the same IP, using a VPN, or other stuff). Unfortunately, there's nothing I can do (of which I'm aware) to work around this.

**Comment by jacksonh** [comment] 2024-05-14 15:23
I'm getting this on all requests now too. I wonder if Google recently deployed something for this.

**Comment by jacksonh** [comment] 2024-05-14 15:24
> I'm getting this on all requests now too. I wonder if Google recently deployed something for this.

```
> await client.getVideoTranscript("5A8UUovaSb8"); 
Uncaught:
[FetchError: invalid json response body at https://www.youtube.com/api/timedtext?v=5A8UUovaSb8&ei=sIFDZq6xFOy52roPnd2MkAc&caps=asr&opi=112496729&exp=xbt&xoaf=5&hl=en-GB&ip=0.0.0.0&ipbits=0&expire=1715725344&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cexp%2Cxoaf&signature=CA50B3C8AC657AF47C19E376E92F4A3223DFD927.604DB09FF45AD34E2CE5F96AA9BAAEB2385D5828&key=yt8&kind=asr&lang=en&prettyPrint=false&fmt=json3 reason: Unexpected token < in JSON at position 0] {
  type: 'invalid-json'
}
```

**Comment by jenny4711** [comment] 2024-05-14 21:34
"I think I almost fixed it by adding const { OAuth2Client } = require('google-auth-library');. It seems to work now, but I am still testing, so I can't say it's completely fixed yet."

**Comment by SuspiciousLookingOwl** [comment] 2024-10-26 05:16
I'm going to close this since there's not much I can do to solve this issue, however, you can try using OAuth: https://github.com/SuspiciousLookingOwl/youtubei/issues/113#issuecomment-2439351189

**Closed by SuspiciousLookingOwl** 2024-10-26 05:16 UTC
Labels: bug
