### ISSUE TITLE
Uncaught (in promise) Error: incorrect header check

### ISSUE THREAD

**Issue by Cutlett** [SuspiciousLookingOwl/youtubei#26] opened 2021-09-10 17:50 UTC
I am a noob developer simply trying to use youtubei to get search results. After struggling for days fighting CORS issues, I was able to disable chrome security and finally get some kind of reply other than a cors error. I am unsure if the error below is still due to a CORS as in the Network tab of Chrome Inspect I am able to see the search results but not print them in the console.

Furthermore, I am using Browserify to bundle the code.

**Expected behavior**
Produce an array of search results. The code works fine in the npm runkit. Was hoping to be pushed in the right direction as searching google has not returned much useful information as to Uncaught (in promise) Error: incorrect header check.

**Screenshots**
![t7cIae3](https://user-images.githubusercontent.com/36119991/132895426-c7a2e4a7-03e8-471e-8bc3-03be56c8eb97.png)
![9snGYeu](https://user-images.githubusercontent.com/36119991/132896147-6fbb77da-12d6-4db9-a49b-3f540eb7d536.png)

**Comment by SuspiciousLookingOwl** [comment] 2021-09-10 17:52
Duplicate of https://github.com/SuspiciousLookingOwl/youtubei/issues/10#issuecomment-812250052

This code is intended to be used on Node environment (server) only

**Closed by SuspiciousLookingOwl** 2021-09-10 17:52 UTC
