### ISSUE TITLE
[BUG] Unresolved function or method 

### ISSUE THREAD

**Issue by ajoykarmakar459** [SuspiciousLookingOwl/youtubei#23] opened 2021-08-30 07:09 UTC
These two functions are not working.
```
  const channelVideos = await video.channel.getVideos();
  const channelPlaylists = await video.channel.getPlaylists();
```
Attached screenshot -

<img width="809" alt="Screenshot 2021-08-30 at 12 38 50 PM" src="https://user-images.githubusercontent.com/23628008/131299735-a8b77fa5-2915-4472-8324-07838d32a3d2.png">

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 07:17
The correct method name supposed to be `nextVideos()` and `nextPlaylists()`

https://youtubei.netlify.app/docs/api/classes/channel#methods

**Comment by ajoykarmakar459** [comment] 2021-08-30 07:20
Can I get the all videos from a channel?

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 07:26
Yes, you just need to pass `0` on the param

```js
const channelVideos = await video.channel.getVideos(0);
```

Keep in mind that the library can only fetch 30 videos at a time (due to limitation from Youtube). So if the channel has 200 videos, fetching all of them means that the lib will send 7 requests one at a time, so it might take a while.

**Comment by ajoykarmakar459** [comment] 2021-08-30 07:31
But this isn't working am I missing some important step?

<img width="777" alt="Screenshot 2021-08-30 at 1 01 02 PM" src="https://user-images.githubusercontent.com/23628008/131302543-cb0d2a8b-03fa-4cbb-a144-550afc283f39.png">

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 07:32
My bad, I copy pasted your code 😂 it's supposed to be `nextVideos`, not `getVideos`

```js
const channelVideos = await video.channel.nextVideos(0);
```

**Comment by ajoykarmakar459** [comment] 2021-08-30 07:38
Ok, great man!
One question is, It will be safe to use this library to run in the production app? I mean can we expect the library update from time to time?

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 08:30
I will keep maintaining the library as long as Youtube doesn't keep making breaking changes on the API, but that most likely won't happen anytime soon.

I wouldn't recommend using it on production app, especially if your app sends lots of requests to Youtube, mostly because it's not 100% reliable (because the library isn't using the official Youtube API) and AFAIK it's violates Youtube's TOS, but they most likely won't care if your usage is "low".

Since your problem is solved, I will close this issue now.

**Closed by SuspiciousLookingOwl** 2021-08-30 08:30 UTC

**Comment by ajoykarmakar459** [comment] 2021-08-30 08:52
So If I get high volume traffic in this library what will happen and how the thing can be sorted, Any Idea?

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 09:02
Haven't really used the library on a high traffic app, you might get IP banned from Youtube (never happens to me before). I don't think there are any solution to this except to just use the [Youtube's Official API](https://developers.google.com/youtube/v3)

**Comment by ajoykarmakar459** [comment] 2021-08-30 09:16
Ok, thank you for the feedback.

**Comment by ajoykarmakar459** [comment] 2021-08-30 09:46
Is it possible to get the nextVideos in a paginated way?

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 10:04
Yes, please consult the docs: https://youtubei.netlify.app/docs/api/classes/channel/#nextvideos

```js
let videos = await video.channel.nextVideos();
console.log(videos); // 1st page

videos = await video.channel.nextVideos();
console.log(videos); // 2nd page

videos = await video.channel.nextVideos();
console.log(videos); // 3rd page

console.log(video.channel.videos) // videos from 1st to 3rd page
```

**Comment by ajoykarmakar459** [comment] 2021-08-30 10:07
Yes, I followed the docs but it's should not hold any keys or paginate numbers so If I make the API then it always shows the first few videos. Am I able to clear the problem that is situated?

**Comment by ajoykarmakar459** [comment] 2021-08-30 10:10
If it's a future plan to do that then it will be good option if we can fetch with paginate numbers, the number of videos,

`videos = await video.channel.nextVideos(paginate numbers: 1, number of videos: 20);
`

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 10:41
Ah I see what you mean, unfortunately due to limitation from Youtube, you can only paginate sequentially from 1st page, to 2nd page, and 3rd, and so on. You can't skip to n-th page.

Exposing the pagination key seems like a good idea so you can pass the key to, lets say, client, and have them pass it back to your server so you know which page to fetch, something like:

```ts
const videos = await video.channel.nextVideos();
const paginationKey = video.channel.videoPaginationKey;

res.send({
    videos,
    paginationKey
});

// later when server receives the request
const paginationKey = req.query.key; // sent from client

const videos = await video.channel.nextVideos(paginationKey)
// ...
```

Feature will be tracked [here](https://github.com/SuspiciousLookingOwl/youtubei/issues/24)

**Comment by ajoykarmakar459** [comment] 2021-08-30 11:19
Yes, that I am talking about. You said that now we can only paginate sequentially from 1st page to 2nd page, and 3rd, and so on - so can you please share how can we do that?

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 12:07
I've already shown you on the [previous message](https://github.com/SuspiciousLookingOwl/youtubei/issues/23#issuecomment-908213705), you just need to call `.nextVideos()` multiple times

```ts
const videoOnFirstPage = await video.channel.nextVideos();
const videosOnSecondPage = await video.channel.nextVideos();
const videosOnThirdPage = await video.channel.nextVideos();
```

**Comment by ajoykarmakar459** [comment] 2021-08-30 12:24
Ah Ok.. I thought there was any other function to get the list.
Thank you for the reponse. Best wishes to you and your library.

**Comment by SuspiciousLookingOwl** [comment] 2021-08-30 12:31
Nope, it's only `.nextVideos()`, alternatively you can pass `number` as the first parameter telling how many pages to fetch, for example;
```ts
const videos = await video.channel.nextVideos(7);
```
`videos` now will contain channel's videos from page 1,2,3... through 7.

or as I mentioned before, you can pass `0` to get all videos on the channel

**Comment by musso** [comment] 2022-06-19 08:51
> My bad, I copy pasted your code 😂 it's supposed to be `nextVideos`, not `getVideos`
> 
> ```js
> const channelVideos = await video.channel.nextVideos(0);
> ```

If the channel is having more than 1000 videos, it will create a timeout error

**Comment by SuspiciousLookingOwl** [comment] 2022-06-19 11:15
> If the channel is having more than 1000 videos, it will create a timeout error

@musso appreciate you reporting bugs, but please create a new issue next time for better tracking.

About the timeout error, it's most likely caused by an unstable connection. I successfully fetched all videos from Linus Tech Tips channel (ID: `UCXuqSBlHAE6Xw-yeJA0Tunw`), which has 5796 videos (at the time I write this comment), it took me 46.3 seconds (it sent 194 requests sequentially, each fetch get 30 videos)
